In [1]:
import seaborn as sns

In [2]:
iris_df = sns.load_dataset("iris")

In [3]:
import numpy as np

In [4]:
iris_df.iloc[:, :-1].apply(np.round).head()

   sepal_length  sepal_width  petal_length  petal_width
0           5.0          4.0           1.0          0.0
1           5.0          3.0           1.0          0.0
2           5.0          3.0           1.0          0.0
3           5.0          3.0           2.0          0.0
4           5.0          4.0           1.0          0.0

In [5]:
iris_df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
iris_df.iloc[:, :-1].apply(np.sum)

sepal_length    876.5
sepal_width     458.6
petal_length    563.7
petal_width     179.9
dtype: float64

In [7]:
iris_df.iloc[:, :-1].apply(np.mean)

sepal_length    5.843333
sepal_width     3.057333
petal_length    3.758000
petal_width     1.199333
dtype: float64

In [8]:
iris_df.iloc[:, :-1].apply(np.sum, axis=1)

0      10.2
1       9.5
2       9.4
3       9.4
4      10.2
       ...
145    17.2
146    15.7
147    16.7
148    17.3
149    15.8
Length: 150, dtype: float64

In [9]:
iris_avg = iris_df.iloc[:, :-1].apply(np.average)

In [10]:
iris_avg

sepal_length    5.843333
sepal_width     3.057333
petal_length    3.758000
petal_width     1.199333
dtype: float64

In [11]:
iris_df.iloc[:,:-1].apply(lambda x :x-iris_avg, axis=1).head()

   sepal_length  sepal_width  petal_length  petal_width
0     -0.743333     0.442667        -2.358    -0.999333
1     -0.943333    -0.057333        -2.358    -0.999333
2     -1.143333     0.142667        -2.458    -0.999333
3     -1.243333     0.042667        -2.258    -0.999333
4     -0.843333     0.542667        -2.358    -0.999333

In [12]:
iris_df2 = iris_df.iloc[:,:-1]

In [13]:
iris_df2.apply(lambda x: list(x-iris_avg), axis=1).head()

0    [-0.7433333333333341, 0.4426666666666663, -2.3...
1    [-0.9433333333333334, -0.05733333333333368, -2...
2    [-1.1433333333333335, 0.1426666666666665, -2.4...
3    [-1.243333333333334, 0.04266666666666641, -2.2...
4    [-0.8433333333333337, 0.5426666666666664, -2.3...
dtype: object

In [14]:
iris_df2.apply(lambda x: list(x-iris_avg), axis=1,
               result_type="broadcast").head()

   sepal_length  sepal_width  petal_length  petal_width
0     -0.743333     0.442667        -2.358    -0.999333
1     -0.943333    -0.057333        -2.358    -0.999333
2     -1.143333     0.142667        -2.458    -0.999333
3     -1.243333     0.042667        -2.258    -0.999333
4     -0.843333     0.542667        -2.358    -0.999333

In [15]:
# iris_df2.applymap(lambda x : x**2).head()

In [16]:
iris_df.sepal_length.map(np.round)

0      5.0
1      5.0
2      5.0
3      5.0
4      5.0
      ...
145    7.0
146    6.0
147    6.0
148    6.0
149    6.0
Name: sepal_length, Length: 150, dtype: float64

In [17]:
iris_df.sepal_length.map(np.sum)

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [18]:
import pandas as pd
s = pd.Series([1,2,3, None])

In [19]:
s.map(lambda x : (x, x**2))

0    (1.0, 1.0)
1    (2.0, 4.0)
2    (3.0, 9.0)
3    (nan, nan)
dtype: object

In [20]:
s.map(lambda x : (x, x**2), na_action='ignore')

0    (1.0, 1.0)
1    (2.0, 4.0)
2    (3.0, 9.0)
3           NaN
dtype: object

In [21]:
x = pd.Series(["Hello", "Python", "World"])
x.map({"Hello":'A', "World":'B', "Python":'C'})

0    A
1    C
2    B
dtype: str