In [1]:
import requests
from bs4 import BeautifulSoup

news_url = 'https://news.sbs.co.kr/news/SectionRssFeed.do?sectionId=07&plink=RSSREADER'
news_rss = requests.get(news_url)
news_rss_soup = BeautifulSoup(news_rss.content, 'xml') # pip install lxml
link_list = news_rss_soup.select('item > link')
print(len(link_list))

29

In [2]:
from konlpy.tag import Kkma
kkma = Kkma()

stopwords = set(["연합뉴스", "연합", "기사문의", "문의", "앵커", "기자", "기사", "사진", 
              "뉴스", "제보", "닫기", "보도", "라인", "오늘", "시간", "준비", "이번",
              "관련", "영상편집", "편집", "지적", "영상", "상황", "분석", "발생", 
              "현지", "현지시간", "인터뷰", "디자인"])


news_data = []
for link in link_list:
    news_response = requests.get(link.text) # 본문의 내용을 수집
    news_content_soup = BeautifulSoup(news_response.content, 'html.parser')
    news_content = news_content_soup.select_one('div[itemprop=articleBody]')
    news_nouns = kkma.nouns(news_content.text)
    news_nouns_list = list(filter(lambda word : len(word)>1 , news_nouns))
    news_nouns_list = [t for t in news_nouns_list if t not in stopwords] # 불용어 제거
    news_data.append(news_nouns_list)
    print('.', end='')

.............................

In [3]:
from apyori import apriori
rules = apriori(news_data, min_support=0.25, min_confidence=0.1)
results = list(rules)

In [4]:
len(results)

194

In [5]:
import pandas as pd

result_df = pd.DataFrame(None, columns=["lhs", "rhs", "support", "confidence", "lift"])
for index, row in enumerate(results):
    support = row[1]
    ordered_stat = row[2]
    for ordered_item in ordered_stat:
        lhs = " ".join(x.strip() for x in ordered_item[0])
        rhs = " ".join(x.strip() for x in ordered_item[1])
        confidence = ordered_item[2]
        lift = ordered_item[3]
        result_df.loc[index] = [lhs, rhs, support, confidence, lift]

In [6]:
result_df.head()

  lhs  rhs   support  confidence  lift
0       10  0.344828    0.344828   1.0
1       26  0.482759    0.482759   1.0
2      26일  0.482759    0.482759   1.0
3       국가  0.275862    0.275862   1.0
4       당시  0.275862    0.275862   1.0

In [7]:
pd.options.display.max_rows = 100

In [8]:
result_df.loc[result_df.lhs==""].sort_values(by=["support"], ascending=False)

   lhs     rhs   support  confidence  lift
9           미국  0.758621    0.758621   1.0
22         트럼프  0.551724    0.551724   1.0
5          대통령  0.551724    0.551724   1.0
2          26일  0.482759    0.482759   1.0
1           26  0.482759    0.482759   1.0
10         백악관  0.379310    0.379310   1.0
0           10  0.344828    0.344828   1.0
17          제작  0.310345    0.310345   1.0
18          주장  0.310345    0.310345   1.0
16          전쟁  0.310345    0.310345   1.0
12          사람  0.310345    0.310345   1.0
11          사건  0.310345    0.310345   1.0
6          디지털  0.275862    0.275862   1.0
3           국가  0.275862    0.275862   1.0
4           당시  0.275862    0.275862   1.0
14          언급  0.275862    0.275862   1.0
13          상태  0.275862    0.275862   1.0
8           만찬  0.275862    0.275862   1.0
7       디지털뉴스부  0.275862    0.275862   1.0
15          자신  0.275862    0.275862   1.0
19          지역  0.275862    0.275862   1.0
20          총격  0.275862    0.275862   1.0
21          출입  0.275862    0.275862   1.0

In [9]:
result_df.loc[result_df.lhs.str.contains("미국")].sort_values(by=["lift"], ascending=False)

                     lhs  rhs   support  confidence      lift
180         백악관 총격 출입 미국   만찬  0.275862    1.000000  3.625000
97                 출입 미국   만찬  0.275862    1.000000  3.625000
96                 총격 미국   만찬  0.275862    1.000000  3.625000
181        백악관 총격 미국 트럼프   만찬  0.275862    1.000000  3.625000
182        백악관 출입 미국 트럼프   만찬  0.275862    1.000000  3.625000
151            총격 미국 트럼프   만찬  0.275862    1.000000  3.625000
152            출입 미국 트럼프   만찬  0.275862    1.000000  3.625000
148            백악관 출입 미국   만찬  0.275862    1.000000  3.625000
150             총격 출입 미국   만찬  0.275862    1.000000  3.625000
192     출입 백악관 총격 트럼프 미국   만찬  0.275862    1.000000  3.625000
183         총격 출입 미국 트럼프   만찬  0.275862    1.000000  3.625000
147            백악관 총격 미국   만찬  0.275862    1.000000  3.625000
95                백악관 미국   만찬  0.275862    0.727273  2.636364
149           백악관 미국 트럼프   만찬  0.275862    0.727273  2.636364
118           미국 대통령 26일   26  0.344828    1.000000  2.071429
163       미국 대통령 26일 트럼프   26  0.344828    1.000000  2.071429
120            주장 미국 26일   26  0.275862    1.000000  2.071429
121           미국 26일 트럼프   26  0.344828    1.000000  2.071429
65                미국 26일   26  0.482759    1.000000  2.071429
74                 주장 미국  26일  0.275862    0.888889  1.841270
70                 주장 미국   26  0.275862    0.888889  1.841270
167          출입 총격 미국 만찬  대통령  0.275862    1.000000  1.812500
168         총격 미국 만찬 트럼프  대통령  0.275862    1.000000  1.812500
169         출입 미국 만찬 트럼프  대통령  0.275862    1.000000  1.812500
136            백악관 출입 미국  대통령  0.275862    1.000000  1.812500
127            미국 만찬 트럼프  대통령  0.275862    1.000000  1.812500
134            백악관 미국 사건  대통령  0.275862    1.000000  1.812500
135            백악관 총격 미국  대통령  0.275862    1.000000  1.812500
82                 미국 사건  대통령  0.275862    1.000000  1.812500
84                 출입 미국  대통령  0.275862    1.000000  1.812500
98                미국 트럼프   만찬  0.275862    0.500000  1.812500
85                미국 트럼프  대통령  0.551724    1.000000  1.812500
76                 미국 만찬  대통령  0.275862    1.000000  1.812500
81                백악관 미국  대통령  0.379310    1.000000  1.812500
83                 총격 미국  대통령  0.275862    1.000000  1.812500
178         총격 출입 미국 트럼프  대통령  0.275862    1.000000  1.812500
175         백악관 총격 출입 미국  대통령  0.275862    1.000000  1.812500
187     백악관 총격 만찬 트럼프 미국  대통령  0.275862    1.000000  1.812500
166        백악관 미국 만찬 트럼프  대통령  0.275862    1.000000  1.812500
165         백악관 출입 미국 만찬  대통령  0.275862    1.000000  1.812500
176        백악관 총격 미국 트럼프  대통령  0.275862    1.000000  1.812500
177        백악관 출입 미국 트럼프  대통령  0.275862    1.000000  1.812500
138            미국 사건 트럼프  대통령  0.275862    1.000000  1.812500
125             총격 미국 만찬  대통령  0.275862    1.000000  1.812500
126             출입 미국 만찬  대통령  0.275862    1.000000  1.812500
124            백악관 미국 만찬  대통령  0.275862    1.000000  1.812500
137           백악관 미국 트럼프  대통령  0.379310    1.000000  1.812500
140            총격 미국 트럼프  대통령  0.275862    1.000000  1.812500
139             총격 출입 미국  대통령  0.275862    1.000000  1.812500
164         백악관 총격 미국 만찬  대통령  0.275862    1.000000  1.812500
141            출입 미국 트럼프  대통령  0.275862    1.000000  1.812500
193  출입 백악관 총격 만찬 트럼프 미국  대통령  0.275862    1.000000  1.812500
189      출입 총격 만찬 트럼프 미국  대통령  0.275862    1.000000  1.812500
191     출입 백악관 총격 트럼프 미국  대통령  0.275862    1.000000  1.812500
186      출입 백악관 총격 만찬 미국  대통령  0.275862    1.000000  1.812500
188     출입 백악관 만찬 트럼프 미국  대통령  0.275862    1.000000  1.812500
174        백악관 미국 사건 트럼프  대통령  0.275862    1.000000  1.812500
25                    미국   26  0.482759    0.636364  1.318182
29                    미국  26일  0.482759    0.636364  1.318182
33                    미국  대통령  0.551724    0.727273  1.318182
42                    미국   만찬  0.275862    0.363636  1.318182
122           미국 대통령 트럼프   26  0.344828    0.625000  1.294643
123           미국 대통령 트럼프  26일  0.344828    0.625000  1.294643
75                미국 트럼프  26일  0.344828    0.625000  1.294643
72                미국 대통령  26일  0.344828    0.625000  1.294643
71                미국 트럼프   26  0.344828    0.625000  1.294643
68                미국 대통령   26  0.344828    0.625000  1.294643

In [10]:
find_condition = result_df.lhs.str.contains("전쟁")
result_df.loc[find_condition].sort_values(by=["lift"], ascending=False)

   lhs rhs   support  confidence      lift
51  전쟁  미국  0.310345         1.0  1.318182

In [11]:
find_condition = (result_df.lhs.str.contains("정부")) & (result_df.rhs.str.contains("인증"))
result_df.loc[find_condition].sort_values(by=["support"], ascending=False)

Empty DataFrame
Columns: [lhs, rhs, support, confidence, lift]
Index: []